const prefix = 'POKEMON_LIST'
export const pokemonListTypes = {
  SETPOKEMONS: `${prefix}_SET_POKEMONS`,
  SETGENERATIONS: `${prefix}_SET_GENERATIONS`,
  SETSELECTEDGENERATION: `${prefix}_SET_SELECTED_GENERATION`,
  SETPAGE: `${prefix}_SET_PAGE`,
  SETPERPAGE: `${prefix}_SET_PER_PAGE`,
  HANDLECHANGETEXT: `${prefix}_HANDLE_CHANGE_TEXT`,
  SETISLOADING: `${prefix}_SET_IS_LOADING`,
  SETTOTALPOKEMONS: `${prefix}_SET_TOTAL_POKEMONS`,
  SETWASSEARCHED: `${prefix}_SET_WAS_SEARCHED`
}
